### ISSUE TITLE
JNumber constructor is not a total function

### ISSUE THREAD

**Issue by fommil** [mdedetrich/scala-json-ast#16]
`JNumber` will throw an exception at runtime if (presumably, accidentally) passed a `String`, which is its only public member

https://github.com/mdedetrich/scalajson/blob/master/jvm/src/main/scala/scalajson/ast/JValue.scala#L77-L81

This is a disaster. I do not agree that we should be using `String` to store `Number`.

Also I do not understand why this is called an AST instead of an ADT. An AST is for a programming language, whereas an ADT is for a data type. JSON is a data type.

**Comment by mdedetrich** [comment]
> This is a disaster. I do not agree that we should be using String to store Number.

There is a reason behind this, there is no Scala data type which can properly hold a JSON number (a JSON number is a completely unbounded real number, of which there is no corresponding type in the Scala stdlib). The next candidate could be `BigDecimal` (even though its not completely unbounded, just very large), however because of an issue which @travisbrown discovered (if you use `BigDecimal` with an exponent that is too large, you can pause/crash the JVM process) we had to settle on a `String`.

**Comment by fommil** [comment]
Do whatever you want as internal detail --- just don't make it your **public** constructor with an exception if it doesn't meet the criteria.

**Comment by fommil** [comment]
You shouldn't use scala's `BigDecimal` or `BigInteger` anyway, they are fundamentally broken.

**Comment by travisbrown** [comment]
For what it's worth circe's approach here is to represent JSON numbers as a pair of `BigInteger`s with the same semantics as `BigDecimal`'s unscaled value and scale, but supporting scales bigger than `Int`. This seems to work well enough—it has some performance costs but we can mostly offset them by using simpler representations when we know they're safe—e.g. a `JsonLong` and even a `JsonDecimal` that wraps a string that's been verified to be a valid JSON number.

I don't think using strings to represent JSON numbers is fundamentally "a disaster" (circe does it in some situations for performance), but I definitely agree with @fommil that the construction of AST number values from unvalidated strings should be much less easy to stumble into than it currently is in ScalaJSON.

**Comment by mdedetrich** [comment]
> Do whatever you want as internal detail --- just don't make it your public constructor with an exception if it doesn't meet the criteria.

So your issue is just thats its a constructor in the case class, i.e. https://github.com/mdedetrich/scalajson/blob/master/jvm/src/main/scala/scalajson/ast/JValue.scala#L77

**Comment by travisbrown** [comment]
(As a side note, @fommil, I'd be curious to hear how Scala's `BigDecimal` and `BigInt` are "fundamentally broken". In my personal experience they're unnecessary and somehow make the already pretty terrible `java.math` versions even less pleasant to use, but that seems different from being broken.)

**Comment by mdedetrich** [comment]
> I don't think using strings to represent JSON numbers is fundamentally "a disaster" (circe does it in some situations for performance), but I definitely agree with @fommil that the construction of AST number values from unvalidated strings should be much less easy to stumble into than it currently is in ScalaJSON.

One of the design goals of ScalaJSON was to strike a balance between "simplicity" and "correctness". Although `JNumber` not being total is a problem, its consistent with the rest of the ADT values which have a single value constructor that represents the internal value (apart from `JTrue`/`JFalse`). I am not against changing it, but I would like to see comments from others.

Its really unfortunate because I don't think there is any good solution here, maybe if Spire (https://github.com/non/spire) ever gets into scala platform we can just change the type to be a real.

**Comment by fommil** [comment]
@travisbrown https://github.com/typelevel/scala/issues/95 I guess it's more correct to say that `java.lang.BigDecimal` is fundamentally greedy and doesn't allow wrappers.

@mdedetrich `JNumber`'s constructor is not a total function. Random user `String`s in, (maybe an) exception out. That *is* a disaster.

**Comment by fommil** [comment]
@mdedetrich if you want to trade off complexity for simplicity, just use https://github.com/spray/spray-json/blob/master/src/main/scala/spray/json/JsValue.scala and don't bother trying to handle corner cases, like circe already does exceptionally well.

**Comment by mdedetrich** [comment]
@fommil We can't use that implementation of `JNumber` because you can suspend the JVM with valid data, this was the issue @travisbrown pointed out earlier (its actually a security issue as well for this reason)

`BigDecimal` as a constructor doesn't work for this reason, and other number types (i.e. `Double`) aren't total either (in fact they are even worse because you can lose data silently). Circe gets around this by making their own `BigDecimal` implementation which skirts this security issue of suspending the JVM.

**Comment by mdedetrich** [comment]
@fommil  See https://github.com/scala/slip/pull/28#issuecomment-190261306 for an example

**Comment by fommil** [comment]
I am fully aware of the reasons for not using `BigDecimal` but if you are trading off simplicity and correctness then lift-json (`Double`), spray-json / play-json (`BigDecimal`) are the right way to go. If you want correctness, circe is the way to go. Using a public `String` constructor with an exception brings us into Python realm of safety. At the very least, make it `private` and make the `apply` method do the regex check and return an `Option`.

**Comment by notxcain** [comment]
I agree with @fommil, the use of `String` is what we all try to avoid and it's definitely not the right balance between simplicity and correctness.

**Comment by alexandru** [comment]
Unless there's something I'm missing, the JSON format is not well specified, however it will always follow ECMAScript and what is expressible by ECMAScript.

And as a matter of fact, numbers in ECMAScript are not unbounded, being represented in [IEEE-754](https://en.wikipedia.org/wiki/IEEE_754) double-precision floating point numbers, on 64 bits, within the range of `5e-324` and `1.79E+308` (+/- `Infinity` and `NaN`). So in Scala, that's a `Double`.

Now it is true that ultimately a JSON file is just a text file where you can dump anything in it, including numbers that can only be expressed with fixed point formats, where the conversion to a `Double` would lose precision.

However, also as a matter of fact as imposed by actual usage, on the web what can't be parsed with ECMAScript's `JSON.parse()` is not valid JSON, in other words JSON parsers, by default, should have this behavior:

```javascript
>>> JSON.parse('{ "number": 9007199254740993 }')
Object { number: 9007199254740992 }
```

Also in actual usage, for use-cases where you don't want to lose precision due to floating point arithmetic, numbers get represented as strings:

```javascript
>>> JSON.parse('{ "number": "9007199254740993" }')
Object { number: "9007199254740993" }
```

Now if you want to get fancy, you can always have a `JsonDecimal` or a `JsonLong` type that can do stuff that `JSON.parse()` cannot do, like @travisbrown is saying above. But the default MUST BE that of ECMAScript.

Yes, it's a safer default, because otherwise the producer might not notice the loss of precision that the Javascripts clients can have and these Javascript clients dominate the market. In other words, the fact that JSON comes from "*JavaScript Object Notation*" is still very relevant.

And I haven't even mentioned that numbers in a static language should really be represented as numbers.

**Comment by travisbrown** [comment]
@alexandru I'm curious why you'd argue that the behavior of ECMAScript is relevant here, or how the JSON spec isn't well-specified? [This](http://www.json.org/) seems pretty precise:

![number](https://user-images.githubusercontent.com/316049/27696032-338f9880-5cb6-11e7-9550-d686a64f66c7.gif)

All ECMA-404 additionally says is "JSON is agnostic about numbers… JSON instead offers only the representation of numbers that humans use: a sequence of digits". The fact that JavaScript's `JSON.parse` is a pretty awful implementation doesn't seem like a good reason for libraries that have nothing to do with JavaScript not to support the spec more fully.

**Comment by alexandru** [comment]
Specs are only useful if they are (1) sane and (2) in actual usage (i.e. *de facto*, in addition to *de jure*).

ECMA-404 happened in 2013, ECMAScript and `JSON.parse()` are what defines JSON. When you're saying that `JSON.parse` is awful, you're using as reference an incomplete and mostly wrong specification that happened a decade later.

**Comment by travisbrown** [comment]
More concretely: a large part (probably close to a majority) of the applications I've personally used circe for involve JSON that will never at any point in its life be parsed in JavaScript.

(In many of these cases JSON probably isn't the best serialization format for the use case, but it's simple and the decision was usually made years before I came along.)

In contexts like these, I want to be able to rely on the _actual_ JSON spec, not on what the standard library of some language I don't care about does.

So I think we're talking about two different versions of "JSON", @alexandru. Which is fine. I see circe as a JSON* library, and if other people prefer JSON** libraries, that's cool too—I'll do my best to have circe work together with them, but I'm not going to adopt their semantics.

<sub>* ECMA-404</sub>
<sub>** what JavaScript actually does</sub>

**Comment by farmdawgnation** [comment]
Perhaps it would be constructive to set aside the debate over the spec. I, too, have been a bit concerned that `String` is a part of the public constructor, but having dealt with numbers while writing code for lift-json wholly understanding of _why_ that's the case.

Could the core complaint here be resolved by providing public constructors that take various kinds of numbers and a very annoyingly named constructor that takes a string that should only be used from a deserializer?

Something like:

```scala
JsNumber.newInstance_!(...)
```

or some such?

**Comment by mdedetrich** [comment]
>So I think we're talking about two different versions of "JSON", @alexandru. Which is fine. I see circe as a JSON* library, and if other people prefer JSON** libraries, that's cool too—I'll do my best to have circe work together with them, but I'm not going to adopt their semantics.

This is why there are two AST's in ScalaJSON, the same one is what @alexandru is describing and the unsafe one is the one with all of these corner cases. Also @travisbrown, @alexandru is right when he says that no parser or serializer should produce what the spec completely allows. This is an abomination that Douglas Crockford made when he created a JSON spec out of thin air, even though JavaScript already has JSON defined without these corner cases (I mean honestly there isn't a sane map like datastructure that handles duplicate keys, and it isn't in JavaScript).

@fommil All of your suggestions are worse because they are as simple but less correct. If you care about function totality, BigDecimal will throw in valid numbers and Decimal will lose precision.

I am more open to defining the standard AST to be same according to what's in Javascript, which means it will be stored as a double (and unsafe will continue to use String and throw with invalid number on regex)

**Comment by fommil** [comment]
I never recommended that you use BigDecimal, my recommendation is that people use lift if they want Double, play or spray if they want BigDecimal, and circe if they want it done right. I don't mean copy them, I mean just use those libraries. Creating something new, that is worse than anything we have, and then having it blessed by EPFL is the worst of all worlds.

**Comment by mdedetrich** [comment]
> I never recommended that you use BigDecimal, my recommendation is that people use lift if they want Double, play or spray if they want BigDecimal, and circe if they want it done right.

Thats probably the worst recommendation out of everything. This means there is no sanity or correctness in how you want to parse JSON (in Scala world or otherwise)

> Creating something new, that is worse than anything we have, and then having it blessed by EPFL is the worst of all worlds.

Objectively this is better than any of your recommendations, it at least doesn't throw exceptions on valid JSON (as per the spec if its what we decide to follow)

**Comment by mdedetrich** [comment]
Okay, so lets clarify a few things. JSON came from Javascript (thats what it stands for, Javascript Object Notation), and before JSON was ratified as a spec by Douglas Crockford (https://tools.ietf.org/html/rfc4627) the specification for JSON was a Javascript Object. In javascript the following properties hold. Also if I have mentioned safe before, I actually meant standard (safe was a confusing term that was used previously in ScalaJSON and dropped, sometimes I have stuck it stuck in my head)

- Javascript objects (i.e. JObject) cannot have duplicate keys, nor does it have any ordering. Its in fact the same as a conventional Map used in other languages (this is very important, since a Map datastructure with these properties allows effectively constant lookup on key, as well as insertion, and these operations are the most common when used on the JSON object)
- All numbers are doubles (if we have a JNumber)

Unfortunately when Douglas Crockford tried to specify a JSON "standard", he added a lot of weasle words in regards to duplicate keys/key ordering/number precision. I am going to make the following categoratizations for the things he added (which he used under the weasle word "should"/"should not")

### Ugly (i.e. really stupid and has no sane reason behind them)
- Duplicate keys in an object
- Ordering in keys (specifically in regards to parsing and serializing, there are corner cases for comparing two JSON objects as equal). To be clear, the insane stupid thing in this case is relying on `JObject` to be ordered, if you need ordering then you use `JArray`.
### Bad (bad but there is some sanity behind this reason)
- JNumber having unlimited precision (restricting them to double makes sense for performance and precision, but now the only way to handle larger numbers is by using strings). Also handling numbers in languages like this is generally messy
### Good
- Everything else, because it actually follows Javascript

The reason above is why ScalaJSON has two AST's. The "sane" (i.e. standard one), and the "unsafe" one. As you can see, `JNumber` is kind of in a grey area, however I am open to making `JNumber` be a `Double` and then the definition of standard AST is just "javascript's implementation" (which honestly is the only sane way to parse/produce JSON and what is also considered good practice)

@travisbrown 
> More concretely: a large part (probably close to a majority) of the applications I've personally used circe for involve JSON that will never at any point in its life be parsed in JavaScript.

The thing is, you mentioned that you don't expect other clients (i.e. Javascript) to parse your JSON spec however actually, no programming languages default parsers would reliably parse Circe's outputted JSON because almost all of the parsers in other languages don't follow the specification as per RFC-4627. In fact, of what I know, the only language which completely follows the specification (including ordered keys and duplicate keys) is Julia (Circe also fails in this regard with really big numbers iirc, however I don't know if this is still the case). If you don't believe me, look at http://seriot.ch/parsing_json.php. Circe is lucky in a few regards since typical usage in Circe with regards to mapping `case class` to JSON means you wont get duplicate keys, however key ordering is something you should never agree to provide. However if a user chooses to do so (i.e. manually construct a Circe `Json`), you can easily produce serialized JSON which a lot of current JSON parsers would parse incorrectly or produce unexpected results for users.

Also if your library expected usage is only for Scala to Scala, there are arguably much better serialization formats (i.e. binary/pickling). My recommendation if its worth anything, is to use a JSON AST which is expected to be parsed by Javascript and doesn't mandate/guarantee anything above it

When @alexandru said
> Specs are only useful if they are (1) sane and (2) in actual usage (i.e. de facto, in addition to de jure).

> ECMA-404 happened in 2013, ECMAScript and JSON.parse() are what defines JSON. When you're saying that JSON.parse is awful, you're using as reference an incomplete and mostly wrong specification that happened a decade later.

He is completely correct. You can follow the spec as much as you want, but if no other client/implementation follows the spec (which in this case there are very good reasons why, the spec is stupid in a lot of areas because it added stuff it shouldn't have when compared to a JSON object which was the previous "standard") then you are probably doing more damage then good.

**Comment by travisbrown** [comment]
@mdedetrich A few things.

> Circe also fails in this regard with really big numbers iirc, however I don't know if this is still the case

If it does this is a bug. I've not seen issues like this since 0.3.0, though, and we now have tests that should cover "really big numbers". 

> you mentioned that you don't expect clients to parse your JSON spec however actually, no programming languages default parsers would reliably parse Circe's outputted JSON

Um, where did I say this? Sure, I guess, if all you mean is that circe may output `9007199254740993` as a JSON document, and a JavaScript client may truncate it to `9007199254740992`. I don't see how that's "less reliable" than circe doing the truncation itself, and both the "safe" and "unsafe" ASTs in ScalaJSON do exactly the same thing:

```scala
scala> scalajson.ast.JNumber("9007199254740993").value
res0: String = 9007199254740993

scala> scalajson.ast.unsafe.JNumber("9007199254740993").value
res1: String = 9007199254740993
```

Similarly ScalaJSON will happily produce numbers that JavaScript will parse as `Infinity`:

```scala
scala> scalajson.ast.JNumber("1.7976931348623157E309").value
res0: String = 1.7976931348623157E309

scala> scalajson.ast.unsafe.JNumber("1.7976931348623157E309").value
res1: String = 1.7976931348623157E309
```

Practically every JSON library on the JVM will do the same thing as circe and ScalaJSON in cases like these. The only different thing about circe is that it can also produce documents like `1e2147483648` (while ScalaJSON, spray-json, etc. can't).

> key ordering is something you should never agree to provide.

I just don't understand this. What circe says is "if you use circe-jawn to parse a JSON document, or if you build up a `Json` value manually, we will preserve the order of object fields". This has nothing to do with the spec, just like it'd have nothing to do with the spec if circe preserved whitespace or associated the position in the input with every AST node or whatever.

Sure, lots of clients may not be able to continue preserving the order once they touch a document circe has serialized, but I don't see how that's any different than it would be if circe didn't preserve field order.

> you can easily produce serialized JSON which a lot of current JSON parsers would parse incorrectly or produce unexpected results for users.

I'd be very interested in seeing an example that doesn't involve big numbers getting truncated, or where the "unexpected results" are markedly different for circe and ScalaJSON. A JSON document serialized by circe will never contain objects with duplicate keys, if that's what you're suggesting the problem would be?

(To be honest I feel like [this whole comment](https://github.com/mdedetrich/scalajson/issues/16#issuecomment-312086085) is pretty inaccurate and FUD-y, but if you've got concrete examples I'd like to see them.)

**Comment by mdedetrich** [comment]
> If it does this is a bug. I've not seen issues like this since 0.3.0, though, and we now have tests that should cover "really big numbers".

In that case its not an issue anymore, I remember in the early days it was a problem (thanks for clarifying)

> Um, where did I say this? Sure, I guess, if all you mean is that circe may output 9007199254740993 as a JSON document, and a JavaScript client may truncate it to 9007199254740992. I don't see how that's "less reliable" than circe doing the truncation itself, and circe is no different in this respect than ScalaJSON right now:

This is just a general issue with dealing with floating precision in programming languages. Hence why `JNumber` is a grey area (I wouldn't classify it as insane, and its why the current standard AST uses a string validated against a regex)

> Similarly ScalaJSON will happily produce numbers that JavaScript will parse as Infinity:

Well actually only the unsafe AST does this, and its documented why. The standard AST would never accept `Infinity` or `NaN`, it has a completely precise regex that only accepts valid JSON numbers (according to the JSON spec)

>I just don't understand this. What circe says is "if you use circe-jawn to parse a JSON document, or if you build up a Json value manually, we will preserve the order of object fields". This has nothing to do with the spec, just like it'd have nothing to do with the spec if circe preserved whitespace or associated the position in the input with every AST node or whatever.

> Sure, lots of clients may not be able to continue preserving the order once they touch a document circe has serialized, but I don't see how that's any different than it would be if circe didn't preserve field order.

Basically the contract is, clients (i.e. code that consumes JSON) should never **rely on the JSON keys being ordered**. If you specify that JObjects are ordered, then that is where the problem arises. This is because a standard map (as it is in Javascript and many other languages, including Java) doesn't preserve ordering on a map

> I'd be very interested in seeing an example that doesn't involve big numbers getting truncated, or where the "unexpected results" are markedly different for circe and ScalaJSON. A JSON document serialized by circe will never contain objects with duplicate keys, if that's what you're suggesting the problem would be?

Like I said earlier, this is a non issue if you don't claim to preserve ordering on JObjects. Its also a non issue for the reasons I mentioned, i.e. case classes can't have duplicate fields so in the majority of cases a Circe Json Object won't have duplicate keys. But if its possible to construct a  Circe Json Object with duplicate keys (and serialize it to JSON that has duplicate keys), then **other** JSON parsers will have unpredictable results in parsing that JSON.

> (To be honest I feel like this whole comment is pretty inaccurate and FUD-y, but if you've got concrete examples I'd like to see them.)

http://seriot.ch/parsing_json.php is as concrete as you can get. This isn't something thats specific to Circe (and I am not trying to be FUD-y, or deliberately single out Circe), I am just pointing out that the JSON specification is **really badly defined**, and in my opinion the best way to handle this is to only deal with the sane subset (which was the original JSON specification, i.e. a Javascript Object).

I prefer to deal with reality, and if in reality almost no parser accepts JSON properly as according to the spec https://tools.ietf.org/html/rfc4627, then it really doesn't make sense to follow the standard tooth and nail and in doing so may cause damage (or you do what ScalaJSON AST has done, and split out these 2 cases). Circe circumvents this insane behaviour because the typical use case of Circe is direct `case class` serialization/deserialization into JSON (which bypasses the really insane parts of the spec), however the underlying AST still allows this unsafe stuff, its just not typically exposed to users.

**Comment by travisbrown** [comment]
> But if its possible to construct a Circe Json Object with duplicate keys (and serialize it to JSON that has duplicate keys), then other JSON parsers will have unpredictable results in parsing that JSON.

As I mentioned above, this is literally impossible—behind the scenes there's a plain old map behind every `io.circe.JsonObject`.

> however the underlying AST still allows this unsafe stuff

I just don't see how this is true, even accepting your characterization of "unsafe", unless having numbers with scales bigger than `Int.MaxValue` is all you mean.

**Comment by mdedetrich** [comment]
> As I mentioned above, this is literally impossible—behind the scenes there's a plain old map behind every io.circe.JsonObject.

Okay my bad, I apologize and retract my comments in this regard (I incorrectly had in my head that Circe maintained duplicate keys)

It does however technically mean you aren't following the full spec, if thats an issue it depends on you.

**Comment by travisbrown** [comment]
> clients (i.e. code that consumes JSON) should never rely on the JSON keys being ordered.

Speaking of reality, this is something many, many JSON users do rely on, and I don't see how guaranteeing it _within the boundaries of a particular library_ to support those users can be construed as a negative thing.

**Comment by mdedetrich** [comment]
> Speaking of reality, this is something many, many JSON users do rely on, and I don't see how guaranteeing it within the boundaries of a particular library to support those users can be construed as a negative thing.

Well seeing as the most common consumers of JSON are in Javascript (either client in browser or node.js), and the most common Ruby parsers parse a Json Object as a map (in which in both cases you lose ordering), those users are relying on something they shouldn't rely on, and I don't think they are "many" users.

**Comment by travisbrown** [comment]
> those users should definitely not be relying on the map being ordered

Everyone should also drive under the speed limit at all times. 😄 

Seriously, though, any library provides all kinds of facilities and conveniences that may not be available in other libraries or languages. I don't see how this is any different, assuming it's made really clear to users that once they print a `Json` value it's their responsibility to check their assumptions.

**Comment by mdedetrich** [comment]
> Seriously, though, any library provides all kinds of facilities and conveniences that may not be available in other libraries or languages. I don't see how this is any different, assuming it's made really clear to users that once they print a Json value it's their responsibility to check their assumptions.

Well, this is what happens when you have a badly defined spec :(

Honestly it makes sense not to rely on JObject key ordering, in original JSON (i.e. javascript), a JObject is a javascript object which has no concept of ordering, just like a Map in many other languages.

If a user relies on this kind of ordering, whoever is producing the JSON should be told not to produce ordered json and/or the user should be told to stop relying on ordering

**Comment by travisbrown** [comment]
> the user should be told to stop relying on ordering

This response kind of sums up my whole issue with SLIP-28 and ScalaJSON: this just isn't the way software development works.

In my experience there are lots of aspects of the way software developers do software development that you can motivate them to change. For example circe is very opinionated about purity, and people who use it have to decide whether they're cool with that or whether they'd prefer a different JSON library.

There are lots of other aspects of the way people work that it's just obnoxious to try to get them to change. If I'm on a team at a large company and a service that depends on my team's service relies on the order of the fields in JSON objects I'm sending them, the last thing I want to do is go to the developers on the downstream team and say "hey, you need to change your system because the maintainer of the JSON library I'm using says what you're doing is bad".

Same thing with negative zero—I personally think it's mathematically a pretty stupid idea, but people need it, and circe provides it. I'm not going to go to them and say "I don't care if some legacy system you're working with needs signed zeros for numerical stability or whatever, it's a silly idea and the JSON library you're using is no longer going to put up with it".

Telling someone that they don't get a mutable JSON representation or that they have to deal with `Either` results instead of catching exceptions is completely different from telling them that they have to change their requirements because their requirements are bad. It just doesn't feel to me like ScalaJSON is doing a very good job of being opinionated in the right ways and not in the wrong ways, and if it really wants to be _the_ JSON representation for Scala I think that's a big problem.

**Comment by OlegIlyenko** [comment]
> Well seeing as the most common consumers of JSON are in Javascript (either client in browser or node.js), and the most common Ruby parsers parse a Json Object as a map (in which in both cases you lose ordering)

Sorry, but this is not true.  

Javascript `Object` preserves the insertation order [accoding to the specification](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) and it is supported by all major browsers and nodejs:

> 3. For each own property key P of O that is a String but is not an integer index, in property creation order

The [same is true](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) for javascript `Map`:

> A Map object iterates its elements in insertion order

In Ruby, JSON objects as well as `Hash` do preserve [an insertation order](https://docs.ruby-lang.org/en/2.0.0/Hash.html):

> Hashes enumerate their values in the order that the corresponding keys were inserted.

**Comment by OlegIlyenko** [comment]
Moreover, we should not forget that machines are not the only consumers of JSON. It is often consumed by human beings. It would be very confusing and frustrating experience if, for instance, every time you make an API call, you get all fields in a random order. This is one of the reasons why most of the languages and libraries do preserve the insertion order.

When it comes to machine-to-machine communication, I know at least one concrete real-world usage of key ordering. [GraphQL specification](https://facebook.github.io/graphql/#sec-Objects) does define the order of keys in the response object (which is JSON in most scenarios):

> This selection of fields will yield an ordered map containing exactly the subset of the object queried, which should be represented in the order in which they were queried.

It is defined as `should`, thus is not considered significant. Facebook, for instance, uses this key-ordering aspect to generate specialized JSON parsers that significantly improve CPU and memory usage on a low-spec mobile devices. The important aspect of this optimization is that the order of the keys is defined by the client (with GraphQL query) and not by the server.

**Comment by mdedetrich** [comment]
@OlegIlyenko Actually now I remember this issue from ages ago (see https://github.com/json4s/json4s-ast/issues/8), I wanted to use a Map that maintained insertion order in Scala however no such collection existed in the stdlib (which is immutable). Seems like I may have to bite the bullet and implement such a collection, either using the implementation from Argonaut (see https://github.com/argonaut-io/argonaut/blob/master/argonaut/shared/src/main/scala/argonaut/JsonObject.scala) or the method described here by Alex (see https://stackoverflow.com/a/9313962/1519631).

Curious, how did you solve the insertion order yourself, did you build you own custom collection? I think that Scala users have circumvented this issue because immutable Map construction does preserve the key order, it just doesn't maintain it when you do immutable copies.

**Comment by OlegIlyenko** [comment]
As far I'm aware, the `scala.collection.immutable.ListMap` was in stdlib [for a while now](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/ListMap.scala#L25). I use it in cases where I need to preserve an insertion order and I don't have a strong performance requirements.

That said, I would not recommend `ListMap` for `JObject` implementation:

>  As such, methods such as `head` and `tail` are O(n), while `last` and `init` are O(1). Other operations, such as inserting or removing entries, are also O(n), which makes this collection suitable only for a small number of elements.

I like the solution that Argonaut and Circe employ, where they store the key-value pairs in the hash map for a fast retrieval and the key ordering information is stored in a separate list. It works quite good in practice.

When I'm working with a JSON library as a user, most of the time i'm working with a sequence of key-value pairs which I then use to create a `JObject`/`JsObject`/`Json`/etc.

When I'm working on a library code and an internal API, I found that in some cases it is very helpful to take advantage of specific scenarios when the JSON object is created. For example this is an internal Map/Object builder i use:

https://github.com/sangria-graphql/sangria-marshalling-api/blob/master/src/main/scala/sangria/marshalling/ArrayMapBuilder.scala

Since I know all keys in advance and know exact access patterns, I can implement it with a simple fixed-size array, `key` → `index` mapping and a set of preset keys. It adds very little overhead and the object allocation is quite minimal. But again, this data structure is designed and optimised for this very specific scenario and it would be hard to reuse it in more general case.

**Comment by mdedetrich** [comment]
@OlegIlyenko I am using the same implementation that Argonaut uses for JSON object (just generalized as a collection), what are your thoughts of https://github.com/mdedetrich/scalajson/pull/19 ?

**Comment by OlegIlyenko** [comment]
`VectorMap` looks nice, I like it.

**Comment by gmethvin** [comment]
FWIW, circe's approach is definitely more compatible with other possible JSON implementations, and the main reasons for still using `BigDecimal` in play-json are simplicity and backwards compatibility. If I were designing the library from scratch I may have done it differently.

That said, it's important to note that the JSON spec allows us to set limits on the numbers that are supported (see http://rfc7159.net/rfc7159#rfc.section.6):

> This specification allows implementations to set limits on the range and precision of numbers accepted. Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision. A JSON number such as 1E400 or 3.141592653589793238462643383279 may indicate potential interoperability problems, since it suggests that the software that created it expects receiving software to have greater capabilities for numeric magnitude and precision than is widely available.

I think what @fommil is getting at here is that everyone has different opinions about the tradeoffs. If your goal is for libraries to replace their AST with this one, then you need to be better or at least as good as what they already have, based on whatever the library's goals are. I think an integration API similar to reactive streams is much more feasible.

**Comment by mdedetrich** [comment]
@gmethvin I understand what @fommil concerns are, but his stated issue wasn't technically accurate. If he cared about the constructor being total, then using `BigDecimal` is actually worse (since it will throw exceptions on very large numbers and in older JVM's you can actually suspend the JVM for a period of time). Doubles are the easiest option, but spray-json (which is what he used as a reference) doesn't actually use Double's (and the biggest issues with doubles is you silently lose precision on the number, which may be a good or a bad thing). If you care about correctness and isomorphism, then actually storing the number internally as a string is the only option (since there is no unbounded ring real type in scala's stdlib). Circe did something similar where they constructed their own BigDecimal variant.

In any case, `JNumber` is being changed so its the best of all worlds. It will allow you to accept and produce all numbers with similar constructor performance.

**Comment by gmethvin** [comment]
In my view at least if you accept `BigDecimal` in your constructor you're stating in the API that you only accept things representable as `BigDecimal`. How is the constructor not total if it only accepts `BigDecimal` and stores it directly?

**Comment by fommil** [comment]
@mdedetrich please stop misquoting me, you've done it on three threads now. Either you don't understand what I'm saying, which is technically concerning, or you are doing it on purpose, much to your detriment.

I have not recommended that you use BigDecimal, I have recommended from the beginning (in the JSON Wars thread, look it up) that the committee should simply bless one of the many production-hardened implementations if they want a "batteries included" scala. Personally I'd rather trim the std distribution but - as with most things - I'm probably on my own island in thinking that way.

If ScalaJSON is released with JNumber having a public String constructor, throwing exceptions, it will haunt everybody for years and I will know I tried to do the right thing by requesting that it be changed. I may even have one of my finest whiskies to fully enjoy the schadenfreude.

A private constructor with a companion `def apply(value: String): Option[JNumber]` that does the check would be an acceptable fix. You could bypass the check for Double etc input or in a parser that lives in the same namespace, for performance.

From my perspective, I have now forked spray-json in ensime to avoid the build chain disaster that will ensue, and I use circe in everything else because it is a high quality library that I enjoy using. I hope my only encounter with ScalaJSON library will be when a customer is paying me, in which case this probably won't even be in the top ten list of bad design decisions to worry about.

**Comment by mdedetrich** [comment]
>  You've done it on three threads now. Either you don't understand what I'm saying, which is technically concerning, or you are doing it on purpose, much to your detriment.

This is your issue that you opened, you are being quoted because you opened the issue and there are multiple people commenting here, this is standard behaviour in online forums.... You also commented in the other threads, so of course you are going to be quoted

> I have not recommended that you use BigDecimal, I have recommended from the beginning (in the JSON Wars thread, look it up) that the committee should simply bless one of the many production-hardened implementations if they want a "batteries included" scala.

You do realise that ScalaJSON (minus the differences with `JNumber` which are being worked through now) is basically a literal copy of spray-json? Have a look at the code, I even worked with @sirthias when making the library

> Personally I'd rather trim the std distribution but - as with most things - I'm probably on my own island in thinking that way.

Except that this isn't going to be part of stdlib, its part of the scala platform (which honestly means that the library is just going to be part of an organization, like TypeLevel), this was clear for over a year. The broken JSON parser in the stdlib was already removed, the stdlib is being trimmed down.

> From my perspective, I have now forked spray-json in ensime to avoid the build chain disaster that will ensue, and I use circe in everything else because it is a high quality library that I enjoy using. I hope my only encounter with ScalaJSON library will be when a customer is paying me, in which case this probably won't even be in the top ten list of bad design decisions to worry about.

Yes, a build disaster that will never happen because both spray-json (JVM) and ScalaJSON AST have the same build dependencies, and both are just libraries (they are not part of the scala standard library). Also if Circe ends up decoupling their `Encoder`/`Decoder`, the ScalaJSON AST will likely be used indirectly (see Future Integration under https://github.com/circe/circe/issues/690#issuecomment-311956866). Also I am working with @travisbrown on the AST.

A lot of time would have been saved if this was discussed in an intellectually honest and constructive way, which would have also cleared a lot of misconceptions which you appear to have (no, ScalaJSON is not being part of the stdlib, there is not going to be a build apocalypse, this AST is a copy of spray-json which was worked on with many people with some changes `JNumber`, the broken JSON parser was removed from stdlib and having a different constructor for `JNumber` is not a disaster). All of this was clear here https://contributors.scala-lang.org/t/scala-json-ast-sp-proposal/175/29

**Comment by fommil** [comment]
This is nothing like `spray-json`. I raised a ticket to ask you not to have a `String` in your public constructor of `JNumber`. That is all this ticket was for. If you choose to ignore my advice, that is your choice.

**Comment by mdedetrich** [comment]
> This is nothing like spray-json. I raised a ticket to ask you not to have a String in your public constructor of JNumber. That is all this ticket was for. If you choose to ignore my advice, that is your choice.

You are not understanding what I am saying. ScalaJSON originally was code that was copied from spray-json (it used to have the same `JNumber` constructor). Then there were numerous issues exposed with the `BigDecimal` constructor later on (voiced by @travisbrown ) hence this is why it was changed. This `JNumber` change has been there for over half a year (at least)

**Comment by fommil** [comment]
duplicated by #22 and #28

**Comment by ShaneDelmore** [comment]
@mdedetrich This ticket seems to have gotten very off-track.  The title is “JNumber constructor is not a total function”.  I agree this is an issue and would love to hear you weigh in on it the issue of JNumber not being total.  I don’t care what spray-json does, or what any other library does, but I do care about throwing exceptions when parsing.
