### ISSUE TITLE
Q: Why JTrue/JFalse?

### ISSUE THREAD

**Issue by farmdawgnation** [mdedetrich/scala-json-ast#4]
Question: Why bother with having `JTrue` and `JFalse`. Is a `JBoolean` that takes a boolean parameter not sufficient here?

**Comment by mdedetrich** [comment]
I believe there was a technical reason for it, but I can't remember right now (maybe @non or @eed3si9n can comment). I think there is an advantage in being able to refer to a Json Boolean by its own type (in certain circumstances).

Also due to `unapply`, it should be transparent for users

**Comment by eed3si9n** [comment]
IANd6, but perhaps it's because there's no mention of "Boolean" in JSON specification. See [Values](https://tools.ietf.org/html/rfc7159#section-3):

> A JSON value MUST be an object, array, number, or string, or one of
> the following three literal names:
> 
> ```
> false null true
> ```
> 
> The literal names MUST be lowercase.  No other literal names are
> allowed.

Another reason might be to avoid the instantiation of new object `JBoolean(true)` during parsing, which incurs memory cost (and GC time cost etc) when you have lots of them.

**Comment by mdedetrich** [comment]
Closing this, question answered
