### ISSUE TITLE
Addition of JNothing

### ISSUE THREAD

**Issue by farmdawgnation** [mdedetrich/scala-json-ast#5]
Something of a suggestion here for the AST. In Lift we have the concept of a `JNothing`.

A `JNothing` is typically the result of an unsuccessful query over some `JValue`. It's distinct from a `JNull` because a `null` is something that could actually appear in the JSON. The `JNothing` literally represents the absence of anything.

For example:

``` scala
scala> import net.liftweb.json._
import net.liftweb.json._

scala> import JsonDSL._
import JsonDSL._

scala> val myObj = ("name" -> "Alice") ~ ("age" -> 24)
myObj: net.liftweb.json.JsonAST.JObject = JObject(List(JField(name,JString(Alice)), JField(age,JInt(24))))

scala> myObj \ "gender"
res0: net.liftweb.json.JsonAST.JValue = JNothing
```

This is especially useful if you're converting one `JObject` into another that may have optional keys. During serialization, `JNothing` just disappears. So if I were to try to construct a new version of Alice using our DSL like so:

``` scala
scala> val newAlice = ("name" -> "Alice") ~ ("age" -> 25) ~ ("gender" -> res0)
newAlice: net.liftweb.json.JsonAST.JObject = JObject(List(JField(name,JString(Alice)), JField(age,JInt(25)), JField(gender,JNothing)))
```

When I render this to an actual JSON string, the key `gender` never appears:

``` scala
scala> compactRender(newAlice)
res2: String = {"name":"Alice","age":25}
```

If I understand the existing AST we have correctly there would be some hoops to jump through to yield this same effect.

**Comment by mdedetrich** [comment]
We had a discussion ages ago around this same issue here https://github.com/json4s/json4s-ast/issues/4 and also in the discussion of the json4s-ast gitter.

We came to the conclusion that since `JNothing` doesn't exist in the AST, it shouldn't be represented there. You also get into the situation where you can't actually claim that `JValue` is a valid representation of JSON.

> If I understand the existing AST we have correctly there would be some hoops to jump through to yield this same effect.

I think this is probably what you are going to need to do. If you have issues in getting around this, let me know, but you may be able to simulate the same effect by using an `Option[JValue]`.

**Comment by mdedetrich** [comment]
I am going to close this now, if it turns out to be a deal breaker then let me know.
